resources:
- ../crds/common
- ../dependencies
- ../operator
- ../scorecard
- ../samples

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: observability-operator
  newName: local-registry:30000/observability-operator
  newTag: 0.0.0-ci

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: observability-operator
      spec:
        template:
          spec:
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                    - key: node-role.kubernetes.io/infra
                      operator: Exists
                  weight: 1
