---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
bases:
  - ../../crds/rhobs-po
resources:
  - namespace.yaml
commonAnnotations:
  package-operator.run/phase: crds
