---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
bases:
- ../../crds/kubernetes
resources:
  - namespace.yaml
commonAnnotations:
  package-operator.run/phase: crds
