---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
images:
- name: observability-operator
  newName: local-registry:30000/observability-operator/observability-operator
  newTag: 0.0.16
bases:
- ../../operator/
commonAnnotations:
  package-operator.run/phase: operator
