---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.rhobs_monitoringstacks.yaml
  - monitoring.rhobs_thanosqueriers.yaml
  - observability-operator.rhobs_configs.yaml

patches:
  patch: |-
    # The following patch make a CRD be a "singleton".
    # Only one CR can be created because validation restricts the value of
    # name.
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      name: configs.observability-operator.rhobs
    spec:
      validation:
        openAPIV3Schema:
          properties:
            metadata:
              properties:
                name:
                  type: string
                  pattern: "config"
