---
apiVersion: apps/v1
kind: Deployment
metadata:
    app.kubernetes.io/part-of: observability-operator
    name: prometheus-operator
spec:
  template:
    spec:
      volumes:
        - name: kubeconfig
          secret:
            defaultMode: 400
            secretName: admin-kubeconfig
      containers:
        - name: prometheus-operator
          volumeMounts:
            - mountPath: /etc/openshift/kubeconfig
              name: kubeconfig
              readOnly: true
          env:
            - name: KUBECONFIG
              value: /etc/openshift/kubeconfig/kubeconfig
